### ISSUE TITLE
wolrdborder fill issue (mc:1.16.5)

### ISSUE THREAD

**Issue by arturek1666** [Puremin0rez/WorldBorder#6]
Hi I had noticed that world is that not all the chunks are fully loaded, this can be notice by simply having a dynmap plugin or other server side map: As example: (This is how my map looks after generating with worldborder what's more I did try to fill it again and it still same issue, it just looks like skipping chunks xd
![image](https://user-images.githubusercontent.com/1558228/120924780-3d103600-c6cd-11eb-9136-c18f529655d7.png)

**Comment by Puremin0rez** [comment]
Unfortunately this is an issue that goes back many years - you can find the references to this issue on the original repository:
https://github.com/Brettflan/WorldBorder/issues/145
https://github.com/Brettflan/WorldBorder/issues/156

You can workaround this issue (hopefully) by adding `true` to the end of your fill command. This forces the loading of every single chunk.
Example: `/wb world fill 1000 208 true`

I am actually fairly confident that I know the exact issue and how to properly fix it if I allocated the time, but the code base just isn't the best and it would be a retrofit for sure. I may or may not do this in the future just for posterity sake of keeping WorldBorder maintained.

I'm just going to recommend Chunky (which does not have this problem, and will fix the issue you see on your map) since it's the modern version of a chunk pregenerator that everyone should be using in my opinion. I've helped quite a bit with it and focus any efforts on that now.

https://github.com/pop4959/Chunky/wiki
https://www.spigotmc.org/resources/chunky.81534/

Hopefully any of the above solves your issue :)

**Comment by arturek1666** [comment]
Looks like if I am doing fill again it still not fixing it:
![image](https://user-images.githubusercontent.com/1558228/125413711-aff04a0d-2ec7-46bb-afe3-ed935700556b.png)
This indeed changed after update but there is still some places not loaded as you can see in the image.
This image shows first fill the secend fill didn't change nothing and yes I did do to force it to load chunks again.

**Comment by arturek1666** [comment]
As the issue can't be fixed closing it.
