### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by AlfreDGR** [Puremin0rez/WorldBorder#7]
Guys will continous with the plugin for 1.17?

**Comment by Puremin0rez** [comment]
Yes! It actually still works fine on 1.17 as it stands right now. Some people have been having issues on Paper (and forks such as Tuinity or Purpur) because of a major bug affecting the servers chunk system. This has been fixed as of their latest server builds.

I'll be making an official 1.17 release sometime next week, but it won't really change anything besides a version bump.

**Comment by Puremin0rez** [comment]
I have published a stable release for 1.17 - you can find it on the releases page or via spigot resources.

https://github.com/Puremin0rez/WorldBorder/releases
https://www.spigotmc.org/resources/worldborder-pures-fork.81706/
